<?php
    //print_r($meettingData);
    helper('form');
    $data=array(array(
        'label'=>'หัวข้อการประชุม',
        'type'=>'text',
        'id'=>'subject',
        'def'=>(isset($meettingData))?$meettingData->subject:'',
        'placeholder'=>'เช่น ประชุมหารือทั่วไป',
        'required'=>true,
         ),
         array(
            'type'=>'hidden',
            'id'=>'id',
            'def'=>(isset($meettingData))?$meettingData->id:'',
             ),
         array(
            'label'=>'ครั้งที่',
            'type'=>'number',
            'id'=>'book_no',
            'def'=>(isset($meettingData))?$meettingData->book_no:'',
            'placeholder'=>'',
            //'required'=>true,
             ),
         array(
            'label'=>'สถานที่ประชุม',
            'type'=>'text',
            'id'=>'meetting_place',
            'def'=>(isset($meettingData))?$meettingData->meetting_place:'',
            'placeholder'=>'เช่น โรงแรมทาวน์อินทาวน์',
            'required'=>true,
             ),
         array(
            'label'=>'วันที่ประชุม',
            'type'=>'date',
            'id'=>'meetting_date',
            'def'=>(isset($meettingData))?$meettingData->meetting_date:date('Y-m-d'),
            'required'=>true,
             ),
         array(
            'label'=>'ผลการประชุม',
            'type'=>'textarea',
            'id'=>'meetting_result',
            'def'=>(isset($meettingData))?$meettingData->meetting_result:'',
            'required'=>true,
             ),
         array(
            'label'=>'ข้อเสนอแนะ',
            'type'=>'textarea',
            'id'=>'meetting_comment',
            'def'=>(isset($meettingData))?$meettingData->meetting_comment:'',
            'required'=>true,
             ),
         array(
            'label'=>'บันทึกการประชุม (สแกนเอกสารบันทึกการประชุมเป็นไฟล์ PDF)'.(isset($meettingData)?' หากไม่ต้องการเปลี่ยนไฟล์ให้ปล่อยว่างไว้':''),
            'type'=>'file',
            'id'=>'meettingRecord',
            'def'=>'',
            'accept'=>'application/pdf',
            'required'=>(isset($meettingData))?false:true,
             ),
         array(
            'label'=>'ภาพถ่ายขณะประชุม (อย่างน้อย 2 ภาพ)'.(isset($meettingData)?' หากไม่ต้องการเปลี่ยนไฟล์ให้ปล่อยว่างไว้':''),
            'type'=>'file',
            'id'=>'pictures',
            'def'=>'',
            'accept'=>'image/jpeg',
            'required'=>(isset($meettingData))?false:true,
            'multiple'=>true,
             ),
         array(
             'label'=>'บันทึกข้อมูล',
             'type'=>'submit',
             'required'=>true,
         ),
    );

    $form=array(
        'formName'=>'ข้อมูลการประชุม',
        'inputs'=>$data,
        'action'=>site_url('public/gov/saveMeetting'),
        'method'=>'post',
        'enctype'=>'multipart/form-data',
    );
    
    print genForm($form);